import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getCommunity, getPost, samplePosts } from "@/lib/community-data";

export function generateStaticParams() { return samplePosts.map((post) => ({ community: post.communitySlug, externalId: post.externalId })); }
export const dynamicParams = false;
export async function generateMetadata({ params }: { params: Promise<{ community: string; externalId: string }> }): Promise<Metadata> { const { community, externalId } = await params; const post = getPost(community, externalId); return post ? { title: `${post.title} | 모아봄`, description: post.summary, alternates: { canonical: `/post/${community}/${externalId}` }, openGraph: { title: post.title, description: post.summary, type: "article" } } : {}; }
export default async function PostPage({ params }: { params: Promise<{ community: string; externalId: string }> }) { const { community, externalId } = await params; const post = getPost(community, externalId); const source = getCommunity(community); if (!post || !source) notFound(); return <main className="post-page"><header className="post-header"><Link href="/" className="community-logo"><span className="community-logo-mark">모</span><span><b>모아봄</b><small>COMMUNITY BRIEF</small></span></Link><Link href={`/community/${community}`} className="post-back">{source.name} 목록 →</Link></header><article className="post-article"><p className="community-eyebrow">{source.name} · 게시글 요약</p><h1>{post.title}</h1><div className="post-meta"><span>{source.name}</span><time dateTime={post.publishedAt}>{new Date(post.publishedAt).toLocaleString("ko-KR")}</time><span>조회 {post.views === null ? "-" : post.views.toLocaleString("ko-KR")}</span><span>추천 {post.likes === null ? "-" : post.likes.toLocaleString("ko-KR")}</span><span>댓글 {post.commentsCount === null ? "-" : post.commentsCount.toLocaleString("ko-KR")}</span></div><div className="post-summary"><strong>모아봄 요약</strong><p>{post.summary}</p></div><div className="post-policy">원문 전체와 댓글은 저장하거나 복제하지 않습니다. 정확한 내용은 출처의 원문에서 확인해 주세요.</div><a className="post-original-button" href={post.originalUrl} target="_blank" rel="noreferrer noopener">원문 보기 <span>↗</span></a></article><footer className="community-footer"><p>모아봄은 원문을 대신하지 않습니다. 출처 링크로 이동해 전체 내용을 확인하세요.</p></footer></main>; }
